---
apiVersion: v1
kind: Secret
metadata:
    name:  {{ include "bot-service-chart.fullname" . }}-secrets
type: Opaque
data:
    BOT_TOKEN: "{{ .Values.botServiceSettings.botToken | default "" | b64enc }}"
    APP_ID: "{{ .Values.botServiceSettings.appId | default "" | b64enc }}"
    DATABASE_PASSWORD: "{{ .Values.botServiceSettings.databasePassword | default "" | b64enc }}"
    DATABASE_LOGIN: "{{ .Values.botServiceSettings.databaseLogin | default "" | b64enc }}"